### PR TITLE
Checkbox untouched

### LINKED ISSUE #78: Required `Checkbox` elements are automatically displaying an error without being touched and without the survey being validated.
**Describe the bug**
`Checkbox` elements with `isRequired: true` are displaying the `isRequired` error immediately upon displaying the survey. To match the web, we should not display the `isRequired` error until the element is either touched, or the survey is validated with none of the choices checked.

**To Reproduce**
SurveyJs json
```json
{
  "questions": [
    {
      "type": "checkbox",
      "name": "question1",
      "isRequired": true,
      "choices": [
        "Item 1",
        "Item 2"
      ]
    }
  ]
}
```

**Expected behavior**
The "question1" element should not display the `isRequired` error message until either the `Checkbox` element is touched or the survey is validated.

**Screenshots**

https://github.com/goxiaoy/flutter_survey_js/assets/27712906/085481e8-d9f6-41d7-b9b5-e3b3244f9b23

**Desktop (please complete the following information):**
N/a

**Smartphone (please complete the following information):**
Any

### PR DESCRIPTION
**Pull request by laogao**
This resolves #78

### CODE REVIEW

**Comment by ChopinDavid** [comment]
I should have mentioned this. My team worked today on converting `Checkbox` to extend `ReactiveFocusableFormField`, which seems to fix the issue in maybe a more thorough way? Curious on your thoughts @laogao https://github.com/wwt/flutter_survey_js/tree/Issue78

**Comment by goxiaoy** [comment]
@laogao 👍 

@ChopinDavid Commented on your commit

**Comment by laogao** [comment]
> I should have mentioned this. My team worked today on converting `Checkbox` to extend `ReactiveFocusableFormField`, which seems to fix the issue in maybe a more thorough way? Curious on your thoughts @laogao

@ChopinDavid I prefer quick and incremental changes when dealing with bugs, to minimize impact. 

That said, it's always good to have healthy conversations on different design & implementation approaches. I would encourage you to open a separate issue to continue this discussion, in order for a wider audience to see and participate.

**Comment by ChopinDavid** [comment]
@laogao That's fair. I am still learning this Reactive Form framework but it seems that `ReactiveFocusableFormField` does a lot of the heavy-lifting for us. If either of you see value in utilizing it, it may just be something to keep in mind. @goxiaoy

**Pull request merged**
