### PR TITLE
Fixed Issue #52: add `showOtherItem` and `showNoneItem` support to `Dropdown`

### PR DESCRIPTION
**Pull request by ChopinDavid**
This would close Issue #52

### CODE REVIEW

**Comment by ChopinDavid** [comment]
I think much of the code in this PR could be refactored to also resolve #33

**Comment by laogao** [comment]
I see a new dependecy being added, namely `equatable`, and a significant portion of this PR seems dedicated to the change.

I'm not against new dependencies or anything. For clarification purposes, may I ask whether this is more of a "self-contained", "future-proof" improvement, or the added `Dropdown` features somehow depends on the ability to compare two objects (I failed to indentify the correspondance between the two)?

**Comment by ChopinDavid** [comment]
See: https://pub.dev/packages/equatable#overview

**Comment by laogao** [comment]
@ChopinDavid Good catch! I guess this could be filed as a separate issue of its own, to make things clear. I do wonder why we haven't been bothered with this behavior so far. Here's what I've learned:

Since the problem is with `didUpdateWidget` call, whenever the screen (viewport) dimensions change, this function is triggered. In addition to focusing and unfocusing a `ReactiveTextField`, which in turn brings up the keyboard, and which in turn (with certain app design/setup) changes the dimensions, when the device orientation changes, say, from vertical to horizontal, it also triggers `didUpdateWidget`.

In our case, firstly, we provided the `onChange` callback so that whenever the input values change we save the state, which later gets feed back into the survey widget through the `answer` field; secondly, we implemented our app in such a way that the keyboard don't mess with screen dimensions whatsoever. As a result, we never lost user input, and the only negative effect we had, as we now came aware of, was when the end users somehow, during their journey with our questionnaire, rotate their phone (given that the rotation is enabled and propagated into our app), they'd be "kicked back" to the start of our questionnaire.

**Comment by ChopinDavid** [comment]
@laogao I was thinking this could be its own issue as well, for the sake of providing a minimally reproducible example. I will probably cherry-pick [f8a8f8c](https://github.com/goxiaoy/flutter_survey_js/pull/53/commits/f8a8f8ccc4a4da2ee9918ec68e990ba957b730f7) onto a new issue/branch/PR and revert it from this Issue52 branch.

**Comment by ChopinDavid** [comment]
@laogao I went ahead and opened Issue #54 and created PR #55 to resolve the `didUpdateWidget` bug. I also went ahead and reverted [f8a8f8c](https://github.com/goxiaoy/flutter_survey_js/pull/53/commits/f8a8f8ccc4a4da2ee9918ec68e990ba957b730f7) on the branch associated with this PR. 🙂

**Pull request merged**
