### PR TITLE
Fixed Issue #54: `SurveyWidget.formGroup` is being reset whenever `didUpdateWidget` is called

### PR DESCRIPTION
**Pull request by ChopinDavid**
This would close Issue #54

See the thread [here](https://github.com/goxiaoy/flutter_survey_js/pull/53) to understand why making `Survey` extend `Equatable` resolves this bug.

### CODE REVIEW

**Comment by goxiaoy** [comment]
This is quite hard to maintain. I am finding a way to generate it from json schema. Just merge it for now

**Comment by ChopinDavid** [comment]
Yes, it would be nice to have `props` auto generate with `JsonSerializable`. I'm sure somebody's encountered a similar issue before.

**Comment by ChopinDavid** [comment]
If you are concerned about maintaining these equatable objects, an alternative to making `Survey` extend `Equatable` would be to replace `survey_widget.dart` lines 157-163 from:

```dart
@override
void didUpdateWidget(covariant SurveyWidget oldWidget) {
  if (oldWidget.survey != widget.survey) {
    rebuildForm();
  }
  super.didUpdateWidget(oldWidget);
}
```

to:

```dart
@override
void didUpdateWidget(covariant SurveyWidget oldWidget) {
  if (oldWidget.survey.toJson().toString() != widget.survey.toJson().toString()) {
    rebuildForm();
  }
  super.didUpdateWidget(oldWidget);
}
```

This way we would not have to worry about manually maintaining `props` on all of these objects.

**Comment by goxiaoy** [comment]
Never mind. I am working on it https://github.com/goxiaoy/flutter_survey_js/tree/gen_model_from_json_schema

**Comment by ChopinDavid** [comment]
I took a look at this branch very briefly. Seems like `built_value` provides both serialization and recursive equatability?

**Pull request merged**
