### PR TITLE
Feature/design changes

### PR DESCRIPTION
**Pull request by Vpdwivedi**

### CODE REVIEW

**Comment by laogao** [comment]
@Vpdwivedi Thanks for the effort in preparing this PR.

I noticed the changes are mainly "cosmetic". Please understand that there is no single best UI style for everyone. Usually we wrap our `s.SurveyWidget` inside a `Theme` widget, and customize from there.

For instance:
```
               final _theme = Theme.of(context);
               ...
               Theme(
                  data: _theme.copyWith(
                    textTheme: _theme.textTheme.copyWith(
                      titleLarge: _theme.textTheme.titleLarge?.copyWith(
                        color: Color(0xFF3070BB),
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                      ),
                      bodyMedium: _theme.textTheme.bodyMedium?.copyWith(
                        color: Color(0xFF3070BB),
                        fontWeight: FontWeight.normal,
                      ),
                    ),
                  ),
                  child: s.SurveyWidget(...),
                )

```

Maybe you would like to try something like above instead? Could be much easier, and much less hustle.

Cheers.

**Comment by Vpdwivedi** [comment]
Thank you so much for your reply. I got your point for the cosmetic changes but apart from this there are other changes like adding a container to put spacing for Cell Label, Column Width Calculation etc. Can you please look into those changes?

Thanks.

**Comment by laogao** [comment]
There seem to be a lot of changes of various aspects. Maybe (before submitting PR containing all these changes) you could file separate issues (one for each) so that others can have a better idea what you intended to improve on? Small (and cohesive) changes are usually easier to manage and put through, once consenses are reached .

**Comment by Vpdwivedi** [comment]
Agreed, will do that.
Thank you again for your guidance. 👍

**Comment by goxiaoy** [comment]
Thanks

**Pull request merged**
